import type { Transformation } from './types';

export const TRANSFORMATIONS: Transformation[] = [
  // Newly added templates from user examples
  {
    key: "streetViewFromMap",
    titleKey: "transformations.effects.streetViewFromMap.title",
    prompt: "画出红色箭头看到的内容",
    emoji: "🗺️",
    descriptionKey: "transformations.effects.streetViewFromMap.description",
  },
  {
    key: "sceneFromMultipleImages",
    titleKey: "transformations.effects.sceneFromMultipleImages.title",
    prompt: "一个模特摆姿势靠在粉色宝马车上。她穿着以下物品，场景背景是浅灰色。绿色外星人是一个钥匙扣，挂在粉色手提包上。模特肩上还有一只粉色鹦鹉。旁边坐着一只戴着粉色项圈和金色耳机的哈巴狗",
    emoji: "🧩",
    descriptionKey: "transformations.effects.sceneFromMultipleImages.description",
    maxImages: 6,
  },
  {
    key: "autoEnhance",
    titleKey: "transformations.effects.autoEnhance.title",
    prompt: "这张照片很无聊很平淡。增强它！增加对比度，提升色彩，改善光线使其更丰富，你可以裁剪和删除影响构图的细节",
    emoji: "🌟",
    descriptionKey: "transformations.effects.autoEnhance.description",
  },
  {
    key: "characterSheet",
    titleKey: "transformations.effects.characterSheet.title",
    prompt: "为我生成人物的角色设定（Character Design）\n\n比例设定（不同身高对比、头身比等）\n\n三视图（正面、侧面、背面）\n\n表情设定（Expression Sheet） → 就是你发的那种图\n\n动作设定（Pose Sheet） → 各种常见姿势\n\n服装设定（Costume Design）",
    emoji: "📝",
    descriptionKey: "transformations.effects.characterSheet.description",
  },
  {
    key: "hairstyleGrid",
    titleKey: "transformations.effects.hairstyleGrid.title",
    prompt: "以九宫格的方式生成这个人不同发型的头像",
    emoji: "💇",
    descriptionKey: "transformations.effects.hairstyleGrid.description",
  },
  {
    key: "dishFromIngredients",
    titleKey: "transformations.effects.dishFromIngredients.title",
    prompt: "用这些食材为我做一顿美味的午餐，放在盘子里，盘子的特写视图，移除其他盘子和食材",
    emoji: "🍳",
    descriptionKey: "transformations.effects.dishFromIngredients.description",
  },
  {
      key: "virtualTryOn",
      titleKey: "transformations.effects.virtualTryOn.title",
      prompt: "选择图1中的人，让他们穿上图2中的所有服装和配饰。在户外拍摄一系列写实的OOTD风格照片，使用自然光线，时尚的街头风格，清晰的全身镜头。保持图1中人物的身份和姿势，但以连贯时尚的方式展示图2中的完整服装和配饰",
      emoji: "👗",
      descriptionKey: "transformations.effects.virtualTryOn.description",
      isMultiImage: true,
      primaryUploaderTitle: "transformations.effects.virtualTryOn.uploader1Title",
      primaryUploaderDescription: "transformations.effects.virtualTryOn.uploader1Desc",
      secondaryUploaderTitle: "transformations.effects.virtualTryOn.uploader2Title",
      secondaryUploaderDescription: "transformations.effects.virtualTryOn.uploader2Desc",
  },
  {
    key: "multiViewModel",
    titleKey: "transformations.effects.multiViewModel.title",
    prompt: "在白色背景上生成前、后、左、右、上、下视图。均匀分布。一致的主体。等距透视等效",
    emoji: "🔄",
    descriptionKey: "transformations.effects.multiViewModel.description",
  },
  {
    key: "movieStoryboard",
    titleKey: "transformations.effects.movieStoryboard.title",
    prompt: "用这个角色创作一个令人上瘾的12部分故事，包含12张图像，讲述经典的黑色电影侦探故事。故事关于他们寻找线索并最终发现的失落的宝藏。整个故事充满刺激，有情感的高潮和低谷，以精彩的转折和高潮结尾。不要在图像中包含任何文字或文本，纯粹通过图像本身讲述故事",
    emoji: "🎬",
    descriptionKey: "transformations.effects.movieStoryboard.description",
  },
  {
    key: "redPenCritique",
    titleKey: "transformations.effects.redPenCritique.title",
    prompt: "分析这张图片。用红笔标出你可以改进的地方。",
    emoji: "🖍️",
    descriptionKey: "transformations.effects.redPenCritique.description",
  },
  {
    key: "isometricFromMap",
    titleKey: "transformations.effects.isometricFromMap.title",
    prompt: "以这个位置为地标，将其设为等距图像（仅建筑物），采用游戏主题公园的风格",
    emoji: "🗺️",
    descriptionKey: "transformations.effects.isometricFromMap.description",
  },
  {
      key: "virtualMakeup",
      titleKey: "transformations.effects.virtualMakeup.title",
      prompt: "为图一人物化上图二的妆，还保持图一的姿势",
      emoji: "💄",
      descriptionKey: "transformations.effects.virtualMakeup.description",
      isMultiImage: true,
      primaryUploaderTitle: "transformations.effects.virtualMakeup.uploader1Title",
      primaryUploaderDescription: "transformations.effects.virtualMakeup.uploader1Desc",
      secondaryUploaderTitle: "transformations.effects.virtualMakeup.uploader2Title",
      secondaryUploaderDescription: "transformations.effects.virtualMakeup.uploader2Desc",
  },
  {
    key: "gundamModel",
    titleKey: "transformations.effects.gundamModel.title",
    prompt: "将照片中的人物转化为高达模型套件包装盒的风格，以等距透视呈现。在包装盒上标注标题“ZHOGUE”。在盒内展示照片中人物的高达风格机械人版本，并伴随其必需品（如化妆品、包袋或其他物品）重新设计为未来派机械配件。包装盒应类似真实的 Gunpla 盒子，包含技术插图、说明书风格细节和科幻字体。在盒子旁边，也展示实际的高达风格机械人本身，在包装外以逼真且栩栩如生的风格渲染，类似于官方 Bandai 宣传渲染图。",
    emoji: "🤖",
    descriptionKey: "transformations.effects.gundamModel.description",
  },
  {
    key: "foodCalorieAnnotation",
    titleKey: "transformations.effects.foodCalorieAnnotation.title",
    prompt: "用食物名称、卡路里密度和近似卡路里来注释这顿饭",
    emoji: "🥗",
    descriptionKey: "transformations.effects.foodCalorieAnnotation.description",
  },
  {
    key: "imageOutpainting",
    titleKey: "transformations.effects.imageOutpainting.title",
    prompt: "将图像的棋盘格部分进行修复，恢复为完整图像",
    emoji: "🖼️",
    descriptionKey: "transformations.effects.imageOutpainting.description",
  },
  {
    key: "sceneFromAncientMap",
    titleKey: "transformations.effects.sceneFromAncientMap.title",
    prompt: "全彩照片。1660 年的新阿姆斯特丹。确保它是全现代色彩，就像它是今天拍摄的照片一样。",
    emoji: "📜",
    descriptionKey: "transformations.effects.sceneFromAncientMap.description",
  },
  {
    key: "fashionMoodboard",
    titleKey: "transformations.effects.fashionMoodboard.title",
    prompt: "时尚情绪板拼贴画。用模特所穿单品的剪纸图案围绕肖像画。用俏皮的马克笔字体添加手写笔记和草图，并用英文标注每件单品的品牌名称和来源。整体美感应该兼具创意和可爱。",
    emoji: "💃",
    descriptionKey: "transformations.effects.fashionMoodboard.description",
  },
  {
    key: "itashaCar",
    titleKey: "transformations.effects.itashaCar.title",
    prompt: "打造一张专业的跑车照片，以动漫风格的人物图案作为“痛车”（彩绘汽车）的设计，拍摄地点为著名的旅游景点或地标。汽车上醒目的大型动漫人物插图，构图简洁干净。人物图案应采用鲜艳的动漫艺术风格，色彩大胆，细节清晰。将车辆放置在自然光线充足的知名旅游景点或风景区，以展现车辆的运动外观和人物图案。运用专业的汽车摄影技巧，并结合适当的景深，突出“痛车”图案，同时融入风景背景，提升旅游吸引力，适合用于促销或爱好者营销材料。",
    emoji: "🏎️",
    descriptionKey: "transformations.effects.itashaCar.description",
  },
  {
    key: "floorplan3d",
    titleKey: "transformations.effects.floorplan3d.title",
    prompt: "帮我把这个住宅平面图转换为房屋的等距照片级真实感 3D 渲染。",
    emoji: "🏠",
    descriptionKey: "transformations.effects.floorplan3d.description",
  },
  {
    key: "idPhoto",
    titleKey: "transformations.effects.idPhoto.title",
    prompt: "截取图片人像头部，帮我做成2寸证件照，要求:\n  1、蓝底\n  2、职业正装\n  3、正脸\n  4、微笑",
    emoji: "🧑‍💼",
    descriptionKey: "transformations.effects.idPhoto.description",
  },
  {
    key: "pirateWantedPoster",
    titleKey: "transformations.effects.pirateWantedPoster.title",
    prompt: "使用原始图像，在羊皮纸上重新绘制一张海盗通缉令。\n棕色单色，带有陈旧羊皮纸的纹理。\n保留原始图像的风格和人物设计，直至最小的细节，并将其大尺寸粘贴在通缉令的顶部。\n脸部特写。让角色戴上海盗帽。\n在海报底部写上赏金金额。赏金金额将是随机的，并使用虚拟的货币单位。\n在赏金金额下方，用小写字母写出罪行。请使用虚拟语言。不得使用英文或中文。",
    emoji: "🏴‍☠️",
    descriptionKey: "transformations.effects.pirateWantedPoster.description",
  },
  {
    key: "lineArtToDoodle",
    titleKey: "transformations.effects.lineArtToDoodle.title",
    prompt: "我上传的图画书看起来就像是一个五岁小孩画的。",
    emoji: "🖍️",
    descriptionKey: "transformations.effects.lineArtToDoodle.description",
  },
  {
    key: "becomeVtuber",
    titleKey: "transformations.effects.becomeVtuber.title",
    prompt: "使用原图创建一个虚拟的Vtuber及其直播画面。\nVtuber的发型和服装将忠实还原原图。\nVtuber的画面为2.5D画质，无需完美还原原图风格，但需要适度的立体感。\nVtuber的表情和姿势可以与原图有所差异。请让Vtuber手持游戏手柄。\n仅将Vtuber的上半身放置在屏幕右下方。将正在游玩的游戏直播画面放置在屏幕中央。将聊天画面放置在屏幕左侧。\n游戏画面的屏幕比例设置为较大，Vtuber的上半身显示较小。\n完全忽略原图的背景和姿势。\n在屏幕的上下添加虚拟的直播平台和浏览器UI。\n生成图像的纵横比与原始图像的纵横比无关。",
    emoji: "🎮",
    descriptionKey: "transformations.effects.becomeVtuber.description",
  },
  {
    key: "makeMoviePoster",
    titleKey: "transformations.effects.makeMoviePoster.title",
    prompt: "分析上传的照片，检测其中的主体、情绪和氛围。\n自动将照片归类到合适的电影类型（爱情、动作、悬疑、恐怖等）。\n\n根据检测到的类型和氛围，用英文生成以下内容：\n- 电影标题：具有冲击力，符合该类型风格。\n- 短标语 / 宣传语：1–2 行，具有戏剧性或情感渲染。\n- 底部制作信息：包括导演、制片、音乐等虚拟姓名，风格类似真实电影海报。\n- 上映信息：如 “COMING SOON” 或 “In Theaters 2025”。\n\n将上述元素叠加在照片上，呈现电影海报风格：\n- 标题显著展示在中央或下三分之一位置。\n- 标语置于标题上方或下方。\n- 制作信息放在底部，文字较小。\n- 上映信息置于底部中央。\n- 最后添加主演信息，格式固定如下：\n\"Starring: <演员姓名>\"\n\n字体要求：粗体、戏剧性、符合电影类型。\n最终效果应看起来像真实的电影院海报，所有元素与照片的情绪和氛围协调一致。",
    emoji: "🍿",
    descriptionKey: "transformations.effects.makeMoviePoster.description",
  },
  {
    key: "fisheyeLens",
    titleKey: "transformations.effects.fisheyeLens.title",
    prompt: "超高细节的动漫插画，采用鱼眼镜头窥视孔视角，呈现圆形扭曲画面，如同透过门上的窥视孔观看，广角扭曲效果，边缘弯曲，圆形边框周围带有暗角。\n画面中两个人将脸靠近窥视孔尝试偷看，都带着调皮顽皮的微笑，透视夸张，使五官显得更大且弯曲，面部靠近窥视孔镜头。\n走廊或房间内部被镜头效果扭曲，边缘略微模糊，模拟真实窥视孔光学效果，氛围俏皮有趣。\n分辨率为 8K。",
    emoji: "👁️",
    descriptionKey: "transformations.effects.fisheyeLens.description",
  },
  {
    key: "customClawMachine",
    titleKey: "transformations.effects.customClawMachine.title",
    prompt: "生成一张图像，展示该动物被简化并变形为动漫风格的毛绒玩具（材质为短绒、触感柔软的聚酯针织布），放置在 UFO 捞娃娃机中。\n\n两侧各有一台额外的 UFO 捞娃娃机，里面摆放着不同动物的毛绒玩具，与主图像的动物不同。\n\n场景设定在日本游戏中心，整体明亮。UFO 捞娃娃机的上部涂有鲜艳颜色，下部涂为白色。背景为墙面，UFO 捞娃娃机背后的区域模糊处理。地面铺有地毯。\n\n拍摄角度为正面。最重要的是，图像中绝对不要出现任何文字或标志。",
    emoji: "🧸",
    descriptionKey: "transformations.effects.customClawMachine.description",
  },
  {
    key: "pixarStyle",
    titleKey: "transformations.effects.pixarStyle.title",
    prompt: "生成一幅 3D 头像：\n\n对象为上传图像中的年轻男性，面带灿烂笑容\n\n背景干净白色\n\n概念数字艺术风格，Pixar 风格\n\n高质量渲染，柔和光照，纹理光滑\n\n色彩鲜明\n\n身体与面部比例真实，但带有卡通感\n\n呈现工作室渲染效果",
    emoji: " Pixar ",
    descriptionKey: "transformations.effects.pixarStyle.description",
  },
  // User-added templates from JSON
  {
    key: "figurineDesign",
    titleKey: "transformations.effects.figurineDesign.title",
    prompt: "Create a 1/7 scale commercialized figurine of the characters in the picture, in a realistic style, in a real environment. The figurine is placed on a computer desk. The figurine has a round transparent acrylic base, with no text on the base. The content on the computer screen is a 3D modeling process of this figurine. Next to the computer screen is a toy packaging box, designed in a style reminiscent of high-quality collectible figures, printed with original artwork. The packaging features two-dimensional flat illustrations.",
    emoji: "🔥",
    descriptionKey: "transformations.effects.figurineDesign.description",
  },
  {
    key: "photoFix",
    titleKey: "transformations.effects.photoFix.title",
    prompt: "This is a technical and stylistic re-rendering of a vintage photograph. The goal is to make this exact scene—with the same people, outfits, poses, and scenery—look as if it were captured today by an elite portrait photographer using modern, professional equipment and a vibrant color grading style. Do not change any element of the scene; instead, fundamentally transform the quality of the image capture itself. 1. Vibrant, Saturated Color Science (New Priority): This is the most important instruction: The color grading must be completely modernized, vibrant, and deeply saturated. Remove every trace of the original's faded, vintage color cast. The final colors should pop with life and energy, emulating a modern digital camera using a 'Vivid' color profile. Specifically: Make any floral patterns rich and bold. Render solid colors as strong, clean, and striking. Ensure all skin tones are warm, healthy, and full of life—completely avoiding a pale, washed-out, or muted appearance. 2. Lighting Transformation: Completely discard the original's harsh, on-camera flash lighting. Re-light the entire scene as if using a professional, off-camera studio setup. Create a large, soft key light from the front-left to sculpt the subjects' faces with gentle, flattering shadows, creating depth and dimension. Add a subtle fill light from the right to soften the shadows. Eliminate the harsh glare on any glasses and create bright, sparkling catchlights in everyone's eyes. 3. Hyper-Realistic Detail and Texture: Render the image with extreme 8K clarity. Skin must look natural, retaining age-appropriate pores and fine lines—strictly avoid a plastic or airbrushed appearance. The fabric textures must be hyper-defined: clearly show any intricate knitting, weaves of patterns, and texture of upholstery. Any wallpaper pattern should be sharp and clear. 4. Modern Camera and Lens Optics: The final image must look like it was captured on a high-end, full-frame digital camera with a sharp 85mm prime lens to create a subtle, natural separation between the subjects and the background. Ensure the dynamic range is wide, with deep, rich blacks and clean, controlled highlights.",
    emoji: "📸",
    descriptionKey: "transformations.effects.photoFix.description",
  },
  {
    key: "homeDesign",
    titleKey: "transformations.effects.homeDesign.title",
    prompt: "This is a photo of an empty living room [Empty Room Photo]. Redesign it in a cozy Scandinavian style. Add a light grey fabric sofa, a natural oak wood coffee table, several green potted plants, and a large, soft wool rug. The lighting should be bright and airy, coming from the window.",
    emoji: "🛋️",
    descriptionKey: "transformations.effects.homeDesign.description",
  },
  {
    key: "noirComicPanel",
    titleKey: "transformations.effects.noirComicPanel.title",
    prompt: "Analyze the input image and convert it into a single, square noir comic panel: preserve the main subject and overall composition, restyle in gritty, high-contrast black-and-white inks with harsh, dramatic lighting, deep blacks, and crisp highlights; add a clean panel border and an optional small caption box area at the top (empty); use strong shadows and subtle rain/atmospheric effects only if they enhance mood; no color, no gradients; final aspect ratio 1:1.",
    emoji: "🕵️",
    descriptionKey: "transformations.effects.noirComicPanel.description",
  },
  {
    key: "miniatureProductAd",
    titleKey: "transformations.effects.miniatureProductAd.title",
    prompt: "A high-resolution advertising photograph of a realistic, miniature this thing held delicately between a person's thumb and index finger. clean and white background, studio lighting, soft shadows. The hand is well-groomed, natural skin tone, and positioned to highlight the product's shape and details. The product appears extremely small but hyper-detailed and brand-accurate, centered in the frame with a shallow depth of field. Emulates luxury product photography and minimalist commercial style.",
    emoji: "🤏",
    descriptionKey: "transformations.effects.miniatureProductAd.description",
  },
  {
    key: "kawaiiSticker",
    titleKey: "transformations.effects.kawaiiSticker.title",
    prompt: "Analyze the input image and extract the main subject. Design a kawaii-style square sticker of that subject: bold, clean outlines, simple cel-shading, vibrant color palette, centered composition, and a pure white background. Keep the subject recognizable while simplifying shapes; add a neat white die-cut border. Avoid text, logos, and busy backgrounds; the result should look like a minimalist commercial sticker.",
    emoji: "💖",
    descriptionKey: "transformations.effects.kawaiiSticker.description",
  },
  {
    key: "amigurumiCrochet",
    titleKey: "transformations.effects.amigurumiCrochet.title",
    prompt: "A high-resolution, studio-lit, hyper-realistic amigurumi product photograph. Transform the main subject (animal or character) from the input image into a handcrafted crochet item, presented on a polished concrete surface. Use three-point softbox lighting to create soft, diffused highlights that eliminate harsh shadows. Shot from a slightly elevated 45-degree angle to showcase clean lines. Features visible yarn texture, stitch details, and soft, felt-like proportions. Has tiny embroidered eyes and simplified facial features. Includes realistic fabric shadows and subtle fuzz for depth of field. Hyperrealistic style with sharp focus point. Neutral gray-toned background for professional presentation. Square 1080x1080 format image.",
    emoji: "🧶",
    descriptionKey: "transformations.effects.amigurumiCrochet.description",
  },
  {
    key: "lineArtExtraction",
    titleKey: "transformations.effects.lineArtExtraction.title",
    prompt: "使用提供的图片，将主要图案/主题的视觉元素精细地转化为纯粹的线条艺术。仅勾勒出图案的轮廓和内部结构线，忽略所有光影、纹理和色彩信息。最终图像应为清晰、简洁的黑白线条图，精确地描绘出原始图案的形状和细节。",
    emoji: "✒️",
    descriptionKey: "transformations.effects.lineArtExtraction.description",
  },
  {
    key: "emotionGrid16",
    titleKey: "transformations.effects.emotionGrid16.title",
    prompt: "Create a 4x4 grid (16 panels total) featuring the upper body character from the input image displaying 16 different exaggerated emotions. Each panel should show only the upper torso and head of the character with dramatically expressive facial expressions and body language. Layout requirements: - Evenly divide the image into 16 equal squares arranged in a 4x4 grid - Separate each panel with thin white lines - Each panel can have different background colors and artistic styles while maintaining consistent character structure - Below each expression, include the corresponding English emotion word in rounded cartoon font style (white text with black outline) Expression variety: Include diverse emotions such as: happy, sad, angry, surprised, confused, excited, sleepy, worried, laughing, crying, shocked, bored, love-struck, frustrated, determined, and silly. Visual style: - Exaggerated and dynamic expressions full of personality and humor - Consistent character design across all 16 panels - Vibrant and varied color schemes for each panel background - Cartoon/anime art style with bold, expressive features - High contrast and clear visibility for all text labels",
    emoji: "😆",
    descriptionKey: "transformations.effects.emotionGrid16.description",
  },
  {
    key: "marbleStatue",
    titleKey: "transformations.effects.marbleStatue.title",
    prompt: "Convert this illustration into a photorealistic marble statue without any paintwork. Faithfully reproduce the character's design and pose, focusing on the figure itself. Render it as a marble statue with a realistic marble surface and detailed shading. Place the statue on a marble pedestal, positioned to cast a soft shadow beneath it. Achieve a fine art photograph-like finish using museum-quality backgrounds, professional lighting, sharp focus, and shallow depth of field.",
    emoji: "🏛️",
    descriptionKey: "transformations.effects.marbleStatue.description",
  },
  {
    key: "vintageTinToy",
    titleKey: "transformations.effects.vintageTinToy.title",
    prompt: "[uploaded image] rendered as vintage tin toy, clockwork key in back; weathered paint chips, micro-scratches, shot on wood workbench with retro tungsten bulb, 100 mm macro, tilt-shift",
    emoji: "🤖",
    descriptionKey: "transformations.effects.vintageTinToy.description",
  },
  {
    key: "waterDropletReflection",
    titleKey: "transformations.effects.waterDropletReflection.title",
    prompt: "Create an ultra-high-definition, photorealistic image of a single crystal-clear water droplet resting on a vibrant green leaf. Inside the droplet, perfectly reflect the content of the uploaded image, ensuring all details of that image are sharply visible and undistorted. Emphasize the intricate texture and veins of the leaf beneath the droplet, and capture realistic light refractions and micro-surface reflections on the water. Use natural, soft ambient lighting to highlight the dew drop's clarity and depth, and maintain a harmonious balance between the organic leaf texture and the urban or subject-specific elements from the uploaded image inside the droplet",
    emoji: "💧",
    descriptionKey: "transformations.effects.waterDropletReflection.description",
  },

  // Prioritized items as requested by the user
  {
    key: "memePack",
    titleKey: "transformations.effects.memePack.title",
    prompt: "生成4宫格的表情包，展现4种不同的表情，分别是喜、怒、哀、乐。纯色背景。",
    emoji: "😂",
    descriptionKey: "transformations.effects.memePack.description",
  },
  {
    key: "knittedDoll",
    titleKey: "transformations.effects.knittedDoll.title",
    prompt: "一张特写、构图专业的照片，展示一个手工钩织的毛线玩偶被双手轻柔地托着。玩偶造型圆润，生成图片1人物的可爱Q版形象，色彩对比鲜明，细节丰富。持玩偶的双手自然、温柔，手指姿态清晰可见，皮肤质感与光影过渡自然，展现出温暖且真实的触感。背景轻微虚化，表现为室内环境，有温暖的木质桌面和从窗户洒入的自然光，营造出舒适、亲密的氛围。整体画面传达出精湛的工艺感与被珍视的温馨情绪。",
    emoji: "🧸",
    descriptionKey: "transformations.effects.knittedDoll.description",
  },
  {
    key: "desktopFigurine",
    titleKey: "transformations.effects.desktopFigurine.title",
    prompt: "将此插画转化为超写实 PVC 动漫手办。需完全保留角色原有的设计、姿势与色彩。将其渲染为 PVC 塑料材质的收藏级手办，表面涂装需高度写实，阴影细节丰富。在头发、衣物等部位添加亮面高光，皮肤则采用哑光质感，同时呈现出真实量产手办中常见的细微合模线。将手办置于简约圆形展示底座上，下方投射柔和阴影。背景是有电脑的办公桌，搭配专业摄影灯光，画面对焦清晰、景深较浅，整体效果如同为产品目录拍摄的实物照片。",
    emoji: "✨",
    descriptionKey: "transformations.effects.desktopFigurine.description",
  },
  {
    key: "giantDoll",
    titleKey: "transformations.effects.giantDoll.title",
    prompt: "现代艺术画廊中，一尊风格化巨型玩偶特写呈现（占据前景主导位置，风格与参考图一致）。上传图片的角色在玩偶旁摆出姿势。玩偶的穿搭与上传角色相呼应。画廊内，白色墙面与天花板天窗相映，背景中挂着带框艺术品。光线方面：采用明亮均匀的画廊室内光。风格特点：整体写实，兼具趣味与艺术氛围，着重突出玩偶巨大的尺寸及其居于画面中心的视觉主导地位。",
    emoji: "🐘",
    descriptionKey: "transformations.effects.giantDoll.description",
  },
  {
    key: "flatLay",
    titleKey: "transformations.effects.flatLay.title",
    prompt: "在一张平铺照片上，展示图中涉及的所有服装单品。",
    emoji: "👕",
    descriptionKey: "transformations.effects.flatLay.description",
  },
  {
    key: "commercialPhoto",
    titleKey: "transformations.effects.commercialPhoto.title",
    prompt: "将上传角色调成商业大片的角色，时尚，高级，服饰、妆容、背景随机调整。",
    emoji: "📸",
    descriptionKey: "transformations.effects.commercialPhoto.description",
  },
  {
    key: "polaroid",
    titleKey: "transformations.effects.polaroid.title",
    prompt: "生成一张亲密合照的拍立得照片。照片带有略微的模糊效果，使用闪光灯在室内拍摄，仿佛派对刚结束。保持亲密又搞笑的姿势，捕捉到轻松有趣的氛围，带有温馨与幽默感",
    emoji: "🎞️",
    descriptionKey: "transformations.effects.polaroid.description",
    maxImages: 4,
  },
  { 
    key: "customPrompt",
    titleKey: "transformations.effects.customPrompt.title", 
    prompt: "CUSTOM", 
    emoji: "✍️",
    descriptionKey: "transformations.effects.customPrompt.description",
    isMultiImage: true,
    isSecondaryOptional: true,
    primaryUploaderTitle: "transformations.effects.customPrompt.uploader1Title",
    primaryUploaderDescription: "transformations.effects.customPrompt.uploader1Desc",
    secondaryUploaderTitle: "transformations.effects.customPrompt.uploader2Title",
    secondaryUploaderDescription: "transformations.effects.customPrompt.uploader2Desc",
  },
  { 
    key: "figurine",
    titleKey: "transformations.effects.figurine.title", 
    prompt: "turn this photo into a character figure. Behind it, place a box with the character’s image printed on it, and a computer showing the Blender modeling process on its screen. In front of the box, add a round plastic base with the character figure standing on it. set the scene indoors if possible", 
    emoji: "🧍",
    descriptionKey: "transformations.effects.figurine.description"
  },
  { 
    key: "cosplay",
    titleKey: "transformations.effects.cosplay.title", 
    prompt: "Generate a highly detailed photo of a girl cosplaying this illustration, at Comiket. Exactly replicate the same pose, body posture, hand gestures, facial expression, and camera framing as in the original illustration. Keep the same angle, perspective, and composition, without any deviation", 
    emoji: "🎭",
    descriptionKey: "transformations.effects.cosplay.description"
  },
  {
    key: "category_effects",
    titleKey: "transformations.categories.effects.title",
    emoji: "✨",
    items: [
      { key: "pixelArt", titleKey: "transformations.effects.pixelArt.title", prompt: "Redraw the image in a retro 8-bit pixel art style.", emoji: "👾", descriptionKey: "transformations.effects.pixelArt.description" },
      { key: "watercolor", titleKey: "transformations.effects.watercolor.title", prompt: "Transform the image into a soft and vibrant watercolor painting.", emoji: "🖌️", descriptionKey: "transformations.effects.watercolor.description" },
      { key: "popArt", titleKey: "transformations.effects.popArt.title", prompt: "Reimagine the image in the style of Andy Warhol's pop art, with bold colors and screen-print effects.", emoji: "🎨", descriptionKey: "transformations.effects.popArt.description" },
      { key: "comicBook", titleKey: "transformations.effects.comicBook.title", prompt: "Convert the image into a classic comic book panel with halftones, bold outlines, and action text.", emoji: "💥", descriptionKey: "transformations.effects.comicBook.description" },
      { key: "claymation", titleKey: "transformations.effects.claymation.title", prompt: "Recreate the image as a charming stop-motion claymation scene.", emoji: "🗿", descriptionKey: "transformations.effects.claymation.description" },
      { key: "ukiyoE", titleKey: "transformations.effects.ukiyoE.title", prompt: "Redraw the image in the style of a traditional Japanese Ukiyo-e woodblock print.", emoji: "🌊", descriptionKey: "transformations.effects.ukiyoE.description" },
      { key: "stainedGlass", titleKey: "transformations.effects.stainedGlass.title", prompt: "Transform the image into a vibrant stained glass window with dark lead lines.", emoji: "🪟", descriptionKey: "transformations.effects.stainedGlass.description" },
      { key: "origami", titleKey: "transformations.effects.origami.title", prompt: "Reconstruct the subject of the image using folded paper in an origami style.", emoji: "🦢", descriptionKey: "transformations.effects.origami.description" },
      { key: "neonGlow", titleKey: "transformations.effects.neonGlow.title", prompt: "Outline the subject in bright, glowing neon lights against a dark background.", emoji: "💡", descriptionKey: "transformations.effects.neonGlow.description" },
      { key: "doodleArt", titleKey: "transformations.effects.doodleArt.title", prompt: "Overlay the image with playful, hand-drawn doodle-style illustrations.", emoji: "✏️", descriptionKey: "transformations.effects.doodleArt.description" },
      { key: "vintagePhoto", titleKey: "transformations.effects.vintagePhoto.title", prompt: "Give the image an aged, sepia-toned vintage photograph look from the early 20th century.", emoji: "📜", descriptionKey: "transformations.effects.vintagePhoto.description" },
      { key: "blueprintSketch", titleKey: "transformations.effects.blueprintSketch.title", prompt: "Convert the image into a technical blueprint-style architectural drawing.", emoji: "📐", descriptionKey: "transformations.effects.blueprintSketch.description" },
      { key: "glitchArt", titleKey: "transformations.effects.glitchArt.title", prompt: "Apply a digital glitch effect with datamoshing, pixel sorting, and RGB shifts.", emoji: "📉", descriptionKey: "transformations.effects.glitchArt.description" },
      { key: "doubleExposure", titleKey: "transformations.effects.doubleExposure.title", prompt: "Create a double exposure effect, blending the image with a nature scene like a forest or a mountain range.", emoji: "🏞️", descriptionKey: "transformations.effects.doubleExposure.description" },
      { key: "hologram", titleKey: "transformations.effects.hologram.title", prompt: "Project the subject as a futuristic, glowing blue hologram.", emoji: "🌐", descriptionKey: "transformations.effects.hologram.description" },
      { key: "lowPoly", titleKey: "transformations.effects.lowPoly.title", prompt: "Reconstruct the image using a low-polygon geometric mesh.", emoji: "🔺", descriptionKey: "transformations.effects.lowPoly.description" },
      { key: "charcoalSketch", titleKey: "transformations.effects.charcoalSketch.title", prompt: "Redraw the image as a dramatic, high-contrast charcoal sketch on textured paper.", emoji: "✍🏽", descriptionKey: "transformations.effects.charcoalSketch.description" },
      { key: "impressionism", titleKey: "transformations.effects.impressionism.title", prompt: "Repaint the image in the style of an Impressionist masterpiece, with visible brushstrokes and a focus on light.", emoji: "👨‍🎨", descriptionKey: "transformations.effects.impressionism.description" },
      { key: "cubism", titleKey: "transformations.effects.cubism.title", prompt: "Deconstruct and reassemble the subject in the abstract, geometric style of Cubism.", emoji: "🧊", descriptionKey: "transformations.effects.cubism.description" },
      { key: "steampunk", titleKey: "transformations.effects.steampunk.title", prompt: "Reimagine the subject with steampunk aesthetics, featuring gears, brass, and Victorian-era technology.", emoji: "⚙️", descriptionKey: "transformations.effects.steampunk.description" },
      { key: "fantasyArt", titleKey: "transformations.effects.fantasyArt.title", prompt: "Transform the image into an epic fantasy-style painting, with magical elements and dramatic lighting.", emoji: "🐉", descriptionKey: "transformations.effects.fantasyArt.description" },
      { key: "graffiti", titleKey: "transformations.effects.graffiti.title", prompt: "Spray-paint the image as vibrant graffiti on a brick wall.", emoji: "🎨", descriptionKey: "transformations.effects.graffiti.description" },
      { key: "minimalistLineArt", titleKey: "transformations.effects.minimalistLineArt.title", prompt: "Reduce the image to a single, continuous, minimalist line drawing.", emoji: "〰️", descriptionKey: "transformations.effects.minimalistLineArt.description" },
      { key: "storybook", titleKey: "transformations.effects.storybook.title", prompt: "Redraw the image in the style of a whimsical children's storybook illustration.", emoji: "📖", descriptionKey: "transformations.effects.storybook.description" },
      { key: "thermal", titleKey: "transformations.effects.thermal.title", prompt: "Apply a thermal imaging effect with a heat map color palette.", emoji: "🌡️", descriptionKey: "transformations.effects.thermal.description" },
      { key: "risograph", titleKey: "transformations.effects.risograph.title", prompt: "Simulate a risograph print effect with grainy textures and limited, overlapping color layers.", emoji: "📠", descriptionKey: "transformations.effects.risograph.description" },
      { key: "crossStitch", titleKey: "transformations.effects.crossStitch.title", prompt: "Convert the image into a textured, handmade cross-stitch pattern.", emoji: "🧵", descriptionKey: "transformations.effects.crossStitch.description" },
      { key: "tattoo", titleKey: "transformations.effects.tattoo.title", prompt: "Redesign the subject as a classic American traditional style tattoo.", emoji: "🖋️", descriptionKey: "transformations.effects.tattoo.description" },
      { key: "psychedelic", titleKey: "transformations.effects.psychedelic.title", prompt: "Apply a vibrant, swirling, psychedelic art style from the 1960s.", emoji: "🌀", descriptionKey: "transformations.effects.psychedelic.description" },
      { key: "gothic", titleKey: "transformations.effects.gothic.title", prompt: "Reimagine the scene with a dark, gothic art style, featuring dramatic shadows and architecture.", emoji: "🏰", descriptionKey: "transformations.effects.gothic.description" },
      { key: "tribal", titleKey: "transformations.effects.tribal.title", prompt: "Redraw the subject using patterns and motifs from traditional tribal art.", emoji: "🗿", descriptionKey: "transformations.effects.tribal.description" },
      { key: "dotPainting", titleKey: "transformations.effects.dotPainting.title", prompt: "Recreate the image using the dot painting technique of Aboriginal art.", emoji: "🎨", descriptionKey: "transformations.effects.dotPainting.description" },
      { key: "chalk", titleKey: "transformations.effects.chalk.title", prompt: "Draw the image as a colorful chalk illustration on a sidewalk.", emoji: "🖍️", descriptionKey: "transformations.effects.chalk.description" },
      { key: "sandArt", titleKey: "transformations.effects.sandArt.title", prompt: "Recreate the image as if it were made from colored sand.", emoji: "🏜️", descriptionKey: "transformations.effects.sandArt.description" },
      { key: "mosaic", titleKey: "transformations.effects.mosaic.title", prompt: "Transform the image into a mosaic made of small ceramic tiles.", emoji: "💠", descriptionKey: "transformations.effects.mosaic.description" },
      { key: "paperQuilling", titleKey: "transformations.effects.paperQuilling.title", prompt: "Reconstruct the subject using the art of paper quilling, with rolled and shaped strips of paper.", emoji: "📜", descriptionKey: "transformations.effects.paperQuilling.description" },
      { key: "woodCarving", titleKey: "transformations.effects.woodCarving.title", prompt: "Recreate the subject as a detailed wood carving.", emoji: "🪵", descriptionKey: "transformations.effects.woodCarving.description" },
      { key: "iceSculpture", titleKey: "transformations.effects.iceSculpture.title", prompt: "Transform the subject into a translucent, detailed ice sculpture.", emoji: "🧊", descriptionKey: "transformations.effects.iceSculpture.description" },
      { key: "bronzeStatue", titleKey: "transformations.effects.bronzeStatue.title", prompt: "Turn the subject into a weathered bronze statue on a pedestal.", emoji: "🗿", descriptionKey: "transformations.effects.bronzeStatue.description" },
      { key: "galaxy", titleKey: "transformations.effects.galaxy.title", prompt: "Blend the image with a vibrant nebula and starry galaxy background.", emoji: "🌌", descriptionKey: "transformations.effects.galaxy.description" },
      { key: "fire", titleKey: "transformations.effects.fire.title", prompt: "Reimagine the subject as if it were formed from roaring flames.", emoji: "🔥", descriptionKey: "transformations.effects.fire.description" },
      { key: "water", titleKey: "transformations.effects.water.title", prompt: "Reimagine the subject as if it were formed from flowing, liquid water.", emoji: "💧", descriptionKey: "transformations.effects.water.description" },
      { key: "smokeArt", titleKey: "transformations.effects.smokeArt.title", prompt: "Create the subject from elegant, swirling wisps of smoke.", emoji: "💨", descriptionKey: "transformations.effects.smokeArt.description" },
      { key: "vectorArt", titleKey: "transformations.effects.vectorArt.title", prompt: "Convert the photo into clean, scalable vector art with flat colors and sharp lines.", emoji: "🎨", descriptionKey: "transformations.effects.vectorArt.description" },
      { key: "infrared", titleKey: "transformations.effects.infrared.title", prompt: "Simulate an infrared photo effect with surreal colors and glowing foliage.", emoji: "📸", descriptionKey: "transformations.effects.infrared.description" },
      { key: "knitted", titleKey: "transformations.effects.knitted.title", prompt: "Recreate the image as a cozy, knitted wool pattern.", emoji: "🧶", descriptionKey: "transformations.effects.knitted.description" },
      { key: "etching", titleKey: "transformations.effects.etching.title", prompt: "Redraw the image as a classic black and white etching or engraving.", emoji: "✒️", descriptionKey: "transformations.effects.etching.description" },
      { key: "diorama", titleKey: "transformations.effects.diorama.title", prompt: "Turn the scene into a miniature 3D diorama inside a box.", emoji: "📦", descriptionKey: "transformations.effects.diorama.description" },
    ]
  },
  { 
    key: "pose",
    titleKey: "transformations.effects.pose.title", 
    prompt: "Apply the pose from the second image to the character in the first image. Render as a professional studio photograph.",
    emoji: "💃",
    descriptionKey: "transformations.effects.pose.description",
    isMultiImage: true,
    primaryUploaderTitle: "transformations.effects.pose.uploader1Title",
    primaryUploaderDescription: "transformations.effects.pose.uploader1Desc",
    secondaryUploaderTitle: "transformations.effects.pose.uploader2Title",
    secondaryUploaderDescription: "transformations.effects.pose.uploader2Desc",
  },
  { 
    key: "expressionReference",
    titleKey: "transformations.effects.expressionReference.title", 
    prompt: "Change the expression of the character in the first image to match the expression of the character in the second image.",
    emoji: "😀",
    descriptionKey: "transformations.effects.expressionReference.description",
    isMultiImage: true,
    primaryUploaderTitle: "transformations.effects.expressionReference.uploader1Title",
    primaryUploaderDescription: "transformations.effects.expressionReference.uploader1Desc",
    secondaryUploaderTitle: "transformations.effects.expressionReference.uploader2Title",
    secondaryUploaderDescription: "transformations.effects.expressionReference.uploader2Desc",
  },
  { 
    key: "lineArt", 
    titleKey: "transformations.effects.lineArt.title", 
    prompt: "Turn the image into a clean, hand-drawn line art sketch.", 
    emoji: "✍🏻", 
    descriptionKey: "transformations.effects.lineArt.description" 
  },
  { 
    key: "colorPalette",
    titleKey: "transformations.effects.colorPalette.title",
    prompt: "Turn this image into a clean, hand-drawn line art sketch.", // Step 1 prompt
    stepTwoPrompt: "Color the line art using the colors from the second image.", // Step 2 prompt
    emoji: "🎨",
    descriptionKey: "transformations.effects.colorPalette.description",
    isMultiImage: true,
    isTwoStep: true,
    primaryUploaderTitle: "transformations.effects.colorPalette.uploader1Title",
    primaryUploaderDescription: "transformations.effects.colorPalette.uploader1Desc",
    secondaryUploaderTitle: "transformations.effects.colorPalette.uploader2Title",
    secondaryUploaderDescription: "transformations.effects.colorPalette.uploader2Desc",
  },
  { 
    key: "iphoneWallpaper",
    titleKey: "transformations.effects.iphoneWallpaper.title", 
    prompt: "Turn the image into an iPhone lock screen wallpaper effect, with the phone's time (01:16), date (Sunday, September 16), and status bar information (battery, signal, etc.), with the flashlight and camera buttons at the bottom, overlaid on the image. The original image should be adapted to a vertical composition that fits a phone screen. The phone is placed on a solid color background of the same color scheme.",
    emoji: "📱",
    descriptionKey: "transformations.effects.iphoneWallpaper.description"
  },
  { 
    key: "sodaCan",
    titleKey: "transformations.effects.sodaCan.title", 
    prompt: "Design a soda can using this image as the main graphic, and show it in a professional product shot.", 
    emoji: "🥤",
    descriptionKey: "transformations.effects.sodaCan.description"
  },
  {
    key: "minimalistIllustration",
    titleKey: "transformations.effects.minimalistIllustration.title",
    prompt: "Turn the people in these images into cute, black and white minimalist illustrations. Each person should be drawn with their unique characteristics and a fitting small prop. The lines should be elegant, and the hair should be a solid black block. Arrange all characters into a single grid image.",
    emoji: "⚫",
    descriptionKey: "transformations.effects.minimalistIllustration.description",
    maxImages: 4,
  },
  // Remaining items from flattened categories
  { 
    key: "funko",
    titleKey: "transformations.effects.funko.title", 
    prompt: "Transform the person into a Funko Pop figure, shown inside and next to its packaging.", 
    emoji: "📦",
    descriptionKey: "transformations.effects.funko.description"
  },
  { 
    key: "lego",
    titleKey: "transformations.effects.lego.title", 
    prompt: "Transform the person into a LEGO minifigure, inside its packaging box.", 
    emoji: "🧱",
    descriptionKey: "transformations.effects.lego.description"
  },
  { 
    key: "crochet",
    titleKey: "transformations.effects.crochet.title", 
    prompt: "Transform the subject into a handmade crocheted yarn doll with a cute, chibi-style appearance.", 
    emoji: "🧶",
    descriptionKey: "transformations.effects.crochet.description"
  },
  { 
    key: "plushie",
    titleKey: "transformations.effects.plushie.title", 
    prompt: "Turn the person in this photo into a cute, soft plushie doll.", 
    emoji: "🧸",
    descriptionKey: "transformations.effects.plushie.description"
  },
  { 
    key: "keychain",
    titleKey: "transformations.effects.keychain.title", 
    prompt: "Turn the subject into a cute acrylic keychain, shown attached to a bag.", 
    emoji: "🔑",
    descriptionKey: "transformations.effects.keychain.description"
  },
  { 
    key: "hdEnhance",
    titleKey: "transformations.effects.hdEnhance.title", 
    prompt: "Enhance this image to high resolution, improving sharpness and clarity.", 
    emoji: "🔍",
    descriptionKey: "transformations.effects.hdEnhance.description"
  },
  { 
    key: "photorealistic",
    titleKey: "transformations.effects.photorealistic.title", 
    prompt: "Turn this illustration into a photorealistic version.", 
    emoji: "🪄",
    descriptionKey: "transformations.effects.photorealistic.description"
  },
  { 
    key: "fashion",
    titleKey: "transformations.effects.fashion.title", 
    prompt: "Transform the photo into a stylized, ultra-realistic fashion magazine portrait with cinematic lighting.", 
    emoji: "📸",
    descriptionKey: "transformations.effects.fashion.description"
  },
  { 
    key: "hyperrealistic",
    titleKey: "transformations.effects.hyperrealistic.title", 
    prompt: "Generate a hyper-realistic, fashion-style photo with strong, direct flash lighting, grainy texture, and a cool, confident pose.", 
    emoji: "✨",
    descriptionKey: "transformations.effects.hyperrealistic.description"
  },
  { 
    key: "architecture",
    titleKey: "transformations.effects.architecture.title", 
    prompt: "Convert this photo of a building into a miniature architecture model, placed on a cardstock in an indoor setting. Show a computer with modeling software in the background.", 
    emoji: "🏗️",
    descriptionKey: "transformations.effects.architecture.description"
  },
  { 
    key: "productRender",
    titleKey: "transformations.effects.productRender.title", 
    prompt: "Turn this product sketch into a photorealistic 3D render with studio lighting.", 
    emoji: "💡",
    descriptionKey: "transformations.effects.productRender.description"
  },
  { 
    key: "industrialDesign",
    titleKey: "transformations.effects.industrialDesign.title", 
    prompt: "Turn this industrial design sketch into a realistic product photo, rendered with light brown leather and displayed in a minimalist museum setting.", 
    emoji: "🛋️",
    descriptionKey: "transformations.effects.industrialDesign.description"
  },
  { 
    key: "isolate",
    titleKey: "transformations.effects.isolate.title", 
    prompt: "Isolate the person in the masked area and generate a high-definition photo of them against a neutral background.", 
    emoji: "🎯",
    descriptionKey: "transformations.effects.isolate.description"
  },
  { 
    key: "screen3d",
    titleKey: "transformations.effects.screen3d.title", 
    prompt: "For an image with a screen, add content that appears to be glasses-free 3D, popping out of the screen.", 
    emoji: "📺",
    descriptionKey: "transformations.effects.screen3d.description"
  },
  { 
    key: "makeup",
    titleKey: "transformations.effects.makeup.title", 
    prompt: "Analyze the makeup in this photo and suggest improvements by drawing with a red pen.", 
    emoji: "💄",
    descriptionKey: "transformations.effects.makeup.description"
  },
  { 
    key: "background",
    titleKey: "transformations.effects.background.title", 
    prompt: "Change the background to a Y2K aesthetic style.", 
    emoji: "🪩",
    descriptionKey: "transformations.effects.background.description"
  },
  { 
    key: "addIllustration",
    titleKey: "transformations.effects.addIllustration.title", 
    prompt: "Add a cute, cartoon-style illustrated couple into the real-world scene, sitting and talking.", 
    emoji: "🧑‍🎨",
    descriptionKey: "transformations.effects.addIllustration.description"
  },
  { 
    key: "paintingProcess", 
    titleKey: "transformations.effects.paintingProcess.title", 
    prompt: "Generate a 4-panel grid showing the artistic process of creating this image, from sketch to final render.", 
    emoji: "🖼️", 
    descriptionKey: "transformations.effects.paintingProcess.description" 
  },
  { 
    key: "markerSketch", 
    titleKey: "transformations.effects.markerSketch.title", 
    prompt: "Redraw the image in the style of a Copic marker sketch, often used in design.", 
    emoji: "🖊️", 
    descriptionKey: "transformations.effects.markerSketch.description" 
  },
  { 
    key: "cyberpunk", 
    titleKey: "transformations.effects.cyberpunk.title", 
    prompt: "Transform the scene into a futuristic cyberpunk city.", 
    emoji: "🤖", 
    descriptionKey: "transformations.effects.cyberpunk.description" 
  },
  { 
    key: "vanGogh", 
    titleKey: "transformations.effects.vanGogh.title", 
    prompt: "Reimagine the photo in the style of Van Gogh's 'Starry Night'.", 
    emoji: "🌌", 
    descriptionKey: "transformations.effects.vanGogh.description" 
  },
];